### ISSUE TITLE
Image issues

### ISSUE THREAD

**Issue by beshizumoto** [vs66388/Hypr-uwu#1]
Hello Bro, why the icons not showed? 
![2023-06-05-152120_hyprshot](https://github.com/vs66388/Hypr-uwu/assets/132457432/73bc3340-e78b-470e-bb6e-d42a225fa23b)
![2023-06-05-152128_hyprshot](https://github.com/vs66388/Hypr-uwu/assets/132457432/b52c53dc-9575-4efa-aff9-5d4e5723edb7)

**Comment by vs66388** [comment]
i mentioned you mightve missed it but here 
1:- ~/.config/eww/scss/windows/powermenu.scss in this line  $assets: '/home/vikash/.config/eww/assets/' change vikash with your username or
2:- just go to ~/.config/eww copy assests folder and file:///home/vikash/.config/eww/assets/ paste it in place of this one

**Comment by beshizumoto** [comment]
yeah its me
also ty it works

**Comment by GlavaNet** [comment]
I'm missing some icons (wifi, notifications, media) on the eww bar even after modifying the HOME path as needed...

**Comment by vs66388** [comment]
oh did it miss it in my readme sorry
