### ISSUE TITLE
Any way to get this on Fedora?

### ISSUE THREAD

**Issue by SharpStormGames** [vs66388/Hypr-uwu#4]
Is there any way to install this on fedora or is it arch linux only?

**Comment by vs66388** [comment]
yes you can and i mentioned it in readme 

well 1st go ahead install fedora and enable rpm repos 
install sway as base than install wlroots and kitty proceed to install hyprland check out hyprland wiki or ypu can find it in rpm repos too install eww-wayland guide on thier github and than gjs ubunutu nerd fonts are avalible in core repos than install brightnessctl alsa-utils and youll find them into core repos to copy paste config install rofi-lbonn-wayland-git or replace it with i recommend wofi instead of building rofi-wayland version and build hyprpaper you are good to go if you dont understand ill make a vedio regarding that imean try too

**Comment by vs66388** [comment]
and btw fedora is my fav distro so all the best buddy

**Comment by SharpStormGames** [comment]
I already have hyprland and eww functioning on a gnome install of fedora, will it still work if i get other necessary packages?

**Comment by vs66388** [comment]
bro i mean it will but you have to manage separate eww config but it will 
go ahead

**Comment by vs66388** [comment]
> I already have hyprland and eww functioning on a gnome install of fedora, will it still work if i get other necessary packages? I only need the font pack, everything else is installed, do you have a download for the font because it doesnt seem to be in the RPM Fusion repos

for font just install font family and paste it into /usr/share/fonts or ~/.fonts it will be fine it is in core repo search fot ubuntu through dnf

**Comment by vs66388** [comment]
> I know where all the config files are dw

i mean than it all great and clear road ahead jump into it

**Comment by vs66388** [comment]
i wanna ask is qt5-wayland and qt6-waylad avalible in dnf core repos

**Comment by SharpStormGames** [comment]
there is qt5-qtwayland and qt6-qtwayland

**Comment by vs66388** [comment]
> there is qt5-qtwayland and qt6-qtwayland

i wanna do it too but i am like on edge regarding that cause i have a wifi 6E card from intel which appreantly dont have drivers on fedora and ubunutu side yet and ill manage that but i have no idea how to setup bminimal install from netiso cause i dont like stuff that i dont use to be on my system sooooo

**Comment by SharpStormGames** [comment]
I have 2 issues and a few questions, 1. I have 2 bluetooth icons whenever connected to a device, 2: Power menu doesnt have any icons (already tried fix in readme, there is no file matching the name in that dir), and I have a few questions: A: Is there anyway to change the arch logo to fedora on the sidebar, B: Can i remove the pencil icon above the quick settings C: Would you recommend any screenshotting utils that are in fedora repos D: Is there a way to remove the empty icon in the quick settings popup

**Comment by vs66388** [comment]
well ill get back to you soon i am still working on fedora i just installed minimal fedora and am working on getting it set up ill tell you when i am done it will be all fedora and work flawlessly with a proper guide

**Comment by vs66388** [comment]
ok screenshoting tool use grim with slurp 
as of null icons which icon is null tell me that icons not appearing in powermenu the file will be ~/.config/eww/scss/powermenu.scss thier are no icons youll see path or search using text editor vikash replace vikash with your user name and itll get fixed as of hyprshot that dropper icon can be removed by going into its file and removing its content ill tell later when ill be using my system thier i as file

**Comment by SharpStormGames** [comment]
alright, cant wait for the proper fedora version! GL with making it

**Comment by vs66388** [comment]
thanks for your petience
