### ISSUE TITLE
Bar is not showing up.

### ISSUE THREAD

**Issue by c4pture** [vs66388/Hypr-uwu#6]
Vertical bar's icons are rendering, but the layout does not. all I have are some vertical icons

**Comment by Vikash-Singh-Tanwar** [comment]
Sry for late reply haven't check in a while so try reinstalling eww it's called eww-git now and as for  windows moving out of screen go into ~/.config/hypr/hyprland.conf thier will be a line in which reserved is mentioned comment that line out and you'll be done

**Comment by Vikash-Singh-Tanwar** [comment]
If bar shows up but is wierd try installing package called sassc

**Comment by c4pture** [comment]
Thank you. The vertical bar is showing up normally. However i'm facing new issues.
1- bottom icons (volume, brightness, battery,etc...) are not aligned correctly. They are positioned on top of each other, but they are a few pixels to the right or left.
2- Any widgets i click on and shows up,won't close. For example if I click on the digital clock positioned at the center of the bar, the calendar widget shows up, but won't close if i click anywhere on the screen, or if i change the brightness of the screen by keyboard keys, the brightness widget shows up at the right of my screen but won't go away. And i have to reboot my OS get rid of it.

Thank you for putting the effort to make this beautiful theme.
